%YAML:1.0
---

#=====================================Detection=====================================#
circularityThreshold: 60 # 圆度阈值
medianBlurSize: 3        # 中值滤波核大小

debug: 0       # debug模式
dilationSize: 9      # 膨胀核大小
erosionSize: 3       # 腐蚀核大小
thresholdValue: 108  # 二值化阈值
thresholdValue_for_roi: 80 # 用于ROI筛选的二值化阈值

rect_area_threshold: 2000 # 矩形面积阈值
circle_area_threshold: 50 # 类圆轮廓面积阈值

length_width_ratio_threshold: 3 # 长宽比阈值

minContourArea: 200 # 最小轮廓面积
target_circle_area_min: 8000
target_circle_area_max: 20000
R_area_min: 800
R_area_max: 2200

#=====================================Identify=====================================#
list_size: 180

d_Radius: 0.7
d_P1P3: 0.254
d_RP2: 0.825

gap: 0
gap_control: 3

tx_cam2cloud: -0.0
# ty_cam2cloud: -1.42
ty_cam2cloud: -1.5
tz_cam2cloud: -0.2

delta_t: 0.03